db:
  image: postgres:latest
  environment:
    POSTGRES_USER: ordermage
    POSTGRES_PASSWORD: thisisatest
  volumes:
    - ./data:/var/lib/postgresql/data
    - ./dbscripts:/docker-entrypoint-initdb.d
  ports:
    - "127.0.0.1:5432:5432"
