name: ordermage

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - bytestring
      - hspec
      - http-client
      - http-types
      - ordermage
      - servant-client
      - warp >= 3.2.4

library:
  source-dirs:
    - src

executables:
  ordermage:
    main: exe/Main.hs
    dependencies:
      - ordermage

dependencies:
  - aeson
  - base
  - bytestring
  - datetime >= 0.3
  - email-validate >= 2
  - envy
  - http-api-data
  - opaleye >= 0.5
  - postgresql-simple
  - product-profunctors
  - servant
  - servant-server
  - text
  - time
  - transformers
  - uuid >= 1.3
  - wai
  - wai-cors
  - warp

